version: "3.8"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: staj-crm-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: staj
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./data/:/var/lib/mysql
    ports:
      - "3308:3306"

  web-service:
    container_name: staj-crm-web
    build: .
    image: staj/spring-boot
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/workspace/app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/staj?autoReconnect=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  node:
    container_name: staj-npm
    image: node:12.16.3
    expose:
      - "8081"
    command: "npm"